const prompt = require('prompt-sync')()
let numero = Number(prompt("Insira o seu número"))

console.log(`${numero} * 1 = ${numero * 1}`)
console.log(`${numero} * 2 = ${numero * 2}`)
console.log(`${numero} * 3 = ${numero * 3}`)
console.log(`${numero} * 4 = ${numero * 4}`)
console.log(`${numero} * 5 = ${numero * 5}`)
console.log(`${numero} * 6 = ${numero * 6}`)
console.log(`${numero} * 7 = ${numero * 7}`)
console.log(`${numero} * 8 = ${numero * 8}`)
console.log(`${numero} * 9 = ${numero * 9}`)
console.log(`${numero} * 10 = ${numero * 10}`)
